<?php
/**
* Import attributes exports generated by "export_asset_attributes" for upgrades
*
* @author David Schoen
* $ID$
*/

require_once dirname(dirname(dirname(__FILE__))).'/init.inc';

$export_dir = 'exported_attributes';

// login as root
$root_user = &$GLOBALS['SQ_SYSTEM']->am->getSystemAsset('root_user');
if (!$GLOBALS['SQ_SYSTEM']->setCurrentUser($root_user)) {
	trigger_error("Failed logging in as root user\n", E_USER_ERROR);
}


$d = dir($export_dir);

while (false !== ($entry = $d->read())) {
	$file = $export_dir.'/'.$entry;
	$id = $entry;
	if (is_file($file) && !preg_match('%done%', $entry)) {
		echo "$id\n";
		import_asset_attributes($id, $file);
		rename($file, $file.'.done') || trigger_error('Failed to rename attr file', E_USER_ERROR);
	}
}

function import_asset_attributes($id, $file) {	
	$attrs = unserialize(file_get_contents($file));
	
	if (!empty($attrs)) {
		$GLOBALS['SQ_SYSTEM']->am->acquireLock($id, 'all');
		
		$asset = $GLOBALS['SQ_SYSTEM']->am->getAsset($id);
		
		foreach ($attrs as $attrName => $attrVal) {
			$asset->setAttrValue($attrName, $attrVal);
		}
		$asset->saveAttributes() || trigger_error('Failed to save attributes', E_USER_ERROR);
		
		$GLOBALS['SQ_SYSTEM']->am->releaseLock($id, 'all');
	}
}

?>
